# Default values for helm-chart-autoscaler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: foo
image_webserver: webserver:latest

microservices:
  webserver: true

webserver:
  cpu_request: "100m"
  memory_limit: "1024Mi"
  minReplicas: 1
  maxReplicas: 100